name: 'Buildah push'
description: 'Pushing docker images with Buildah'
author: 'ixxeL'
inputs:
  image-id:
    description: 'ID or full name of the image to push'
    required: true
  transport:
    description: 'transport type for destination (containers-storage,dir,docker,docker-archive,docker-daemon,oci,oci-archive,ostree)'
    required: true
  destination:
    description: 'The Image "DESTINATION" uses a "transport":"details" format'
    required: true
  format:
    description: 'manifest type (oci, v2s1, or v2s2) to use when saving image using the "dir:" transport (default is manifest type of source)'
    required: false
    default: '""'

runs:
  using: "composite"
  steps:
    - id: buildah-push
      run: |
        echo -e "${BLUE}[ STEP - PUSHING IMAGE ] > Pushing docker image ${{ inputs.image-id }} with buildah.${BLANK}"
        echo -e "${CYAN}[ INFO ] > Buildah version.${BLANK}"
        buildah --version
        echo -e "${YELLOW}[ EXECUTING ] > Executing push of ${{ inputs.image-id }} to ${{ inputs.destination }}.${BLANK}"

        buildah push --format ${{ inputs.format }} \
                     ${{ inputs.image-id }} \
                     ${{ inputs.transport }}:${{ inputs.destination }}
      shell: bash
      env:
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m